version: "3"

services:
  ai_driver_redis:
    image: redis
    ports:
      - 26379:26379
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    - /mnt/e/redis-data/aidriver:/data:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - dd-network

  ai_driver_pg:
    container_name: ai_driver_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ai_driver
    ports:
      - 5432:5432
    networks:
      - dd-network

  ai_driver_jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: ai_driver_jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./.venv:/opt/venv  # Mounting the venv directory
      - ./scripts/notebook_start.sh:/usr/local/bin/start.sh  
      - ./ai_driver/ai_driver:/code
    environment:
      - JUPYTER_ENABLE_LAB=yes
    entrypoint: /bin/bash -c "chmod +x /usr/local/bin/start.sh && /usr/local/bin/start.sh jupyter lab --NotebookApp.custom_display_url=http://127.0.0.1:8888"

    networks:
      - dd-network

  ai_driver_pg_admin:
    container_name: ai_driver_pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root 
    ports:
      - 5050:80
    networks:
      - dd-network


  ai_driver: # ai_driver:28001
    build:
      context: ./ai_driver
      dockerfile: Dockerfile
    container_name: ai_driver
    ports:
      - 28001:28001
    volumes:
      - ./ai_driver/ai_driver:/code
      - ./artifacts:/artifacts
      - ./vectorstore:/vectorstore
      - ./data:/data
      # - ~/.cache/huggingface:/home/appuser/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    networks:
      - dd-network
    depends_on:
      - ai_driver_redis
  webui:
    build:
      context: ./ai_driver
      dockerfile: webui/Dockerfile
    container_name: ai_driver_webui
    ports:
      - 18000:18000
    volumes:
      - ./ai_driver/webui:/code
    env_file:
      - .env
    networks:
      - dd-network
    depends_on:
      - ai_driver

networks:
  dd-network:
    external: true
