# Use the base Jupyter image
FROM jupyter/scipy-notebook:latest

# Copy the start.sh script and set permissions
COPY ./scripts/notebook_start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh
